#!/bin/bash
#SBATCH -J matlab
#SBATCH -N 1
#SBATCH --tasks-per-node=6
#SBATCH -t 700:00:00
#SBATCH -p small-long

/software/MATLAB/R2025b/bin/matlab -nodisplay -nodesktop -nosplash < Rep_Figure_6.m > test6.out

